# PART III c)

In [7]:
import pandas as pd
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit
import numpy as np
%matplotlib qt

In [8]:
def lin(x,m,t):
    return m*x+t

In [9]:
data=pd.read_csv('part3c.csv', index_col=0)
data

x bpm1    x bpm2        q1        q2       dq1        dq2
dp                                                                 
-0.005 -0.001143 -0.001806  6.788327  2.660692  0.303642   6.916810
-0.002 -0.000431 -0.000749  6.790896  2.682702  1.447811   7.768016
 0.000 -0.000009  0.000007  6.794679  2.698843  2.358451   8.380545
 0.002  0.000363  0.000808  6.800436  2.716259  3.430101   9.046475
 0.005  0.000805  0.002109  6.813630  2.745068  5.471275  10.197388

In [10]:
popt, pcov = curve_fit(lin, data.index, data['x bpm1'])
popt

array([ 1.95314672e-01, -8.30169444e-05])

Dispersion in BPM1: 0.195314672 m  (comparison to twiss file: 0.1991774487)

In [11]:
popt2, pcov2 = curve_fit(lin, data.index, data['x bpm2'])
popt2

array([3.91190287e-01, 7.38301908e-05])

Dispersion in BPM2: 0.391190287 m (comparison to twiss file: 0.3891638269)

In [13]:
plt.plot(data['x bpm1'],'o-', label='BPM 1')
plt.plot(data.index, lin(data.index,*popt),'--', label=r'Fit BPM1')
plt.plot(data['x bpm2'],'o-', label='BPM 2')
plt.plot(data.index, lin(data.index,*popt2),'--', label=r'Fit BPM2')
plt.ylabel('x position in m')
plt.xlabel(r'$\Delta p/p$')
plt.legend();

In [14]:
def quad(x,a,b,c):
    return a*x**2+b*x+c

In [15]:
popt3, pcov3 = curve_fit(quad, data.index, data['q1'])
popt3

array([252.51116254,   2.51029574,   6.79466458])

Chromaticity in x direction: 2.51029574 (comparison to twiss file: 2.358451)

In [39]:
plt.plot(data['q1'],'o-', label='Q1')
plt.plot(data.index, quad(data.index,*popt3),'--', label='Fit Q1')
plt.ylabel('Tune')
plt.xlabel(r'$\Delta p/p$')
plt.legend();

In [18]:
popt4, pcov4 = curve_fit(quad, data.index, data['q2'])
popt4

array([161.69368795,   8.43099167,   2.69883723])

Chromaticity in y direction: 8.43099167 (comparison to twiss file: 8.380545)

In [19]:
plt.plot(data['q2'],'o-', label='Q2')
plt.plot(data.index, quad(data.index,*popt4),'--', label='Fit Q2')
plt.ylabel('Tune')
plt.xlabel(r'$\Delta p/p$')
plt.legend();

In [54]:
data['dq2']

dp
-0.005     6.916810
-0.002     7.768016
 0.000     8.380545
 0.002     9.046475
 0.005    10.197388
Name: dq2, dtype: float64

# PART III d)

In [20]:
q1=6.794679
q2=2.698843
beta0x_family1_1=15.51
beta0y_family1_1=9.144
beta0x_family1_2=19.24
l_family3=0.39
l_default=0.32

In [21]:
data2=pd.read_csv('part3d.csv')
data2

family  percent of kq        q1        q2
0       1           0.95  6.229656  2.822544
1       1           1.05  7.147678  2.522961
2       2           0.95  6.902550  2.229925
3       2           1.05  6.660148  3.180405
4       3           0.95  6.601481  2.766610
5       3           1.05  6.979753  2.533548
6       4           0.98  6.817540  2.348782
7       4           1.05  6.711703  3.155252
8       5           0.95  6.496701  2.937224
9       5           1.05  7.033817  2.223021

In [22]:
4*0.25*1./np.pi*(beta0x_family1_1+beta0x_family1_2)*2.1152*0.05*l_default

0.3743487236183105

In [34]:
data2['q1'][1]

7.147677581

In [35]:
q1-data2['q1'][1]

-0.3529985809999996

Just one quad Q1.s1.01 to 105%

In [36]:
q1_single=6.841368071
q2_single=2.642508858

In [37]:
0.25*1./np.pi*(beta0x_family1_1)*2.1152*0.05*l_default

0.0417708539807194

In [38]:
q1-q1_single

-0.046689070999999416

In [27]:
0.25*1./np.pi*(beta0y_family1_1)*2.1152*0.05*l_default

0.024626221070257782

In [28]:
q2-q2_single

0.05633414200000031

# PART III e)

In [29]:
# Sextupols at nominal strength
dq1=2.358451
dq2=8.380545

In [30]:
# Sextupols off
dq1_natural=-13.3469989
dq2_natural=-6.897383668